# Generated by Django 5.1.15 on 2026-08-08 12:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_role_rolepermission_userrole'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Action')),
                ('target_entity_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Entity Type')),
                ('target_entity_id', models.UUIDField(blank=True, null=True, verbose_name='Target Entity ID')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address')),
                ('pre_change_state', models.JSONField(blank=True, null=True, verbose_name='Pre-Change State')),
                ('post_change_state', models.JSONField(blank=True, null=True, verbose_name='Post-Change State')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=512, unique=True, verbose_name='Token')),
                ('device_info', models.TextField(blank=True, null=True, verbose_name='Device Info')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Revoked')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email_lower'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'is_revoked', 'expires_at'], name='idx_refresh_tokens_lookup'),
        ),
    ]
